# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: "docker Build and Push"
      inputs:
        containerRegistry: 'docker-acr-mintt-outlook'
        repository: 'python'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: 'latest'

  